<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>面向对象基础复习03</title>
	<script type="text/javascript">
		//报错将会结束代码的运行，不会执行后续代码

		//	 function fn() {
		// 		console.log(num);
		// 		console.log(123);
		// 	 }

		// 	 fn();
		//   fn();

		//代码的错误是需要处理的，但是又不清楚是否会在这里报错
		//try-catch语法
		//语法：
		// 	 try{
		// 		可能出现的错误
		// 	 }catch{
		// 		如果出现错误，则执行这里
		//   }finally{  //可选，可写可不写
		// 		无论是否出现异常，最后执行
		//   }

		function fn() {
			try{
				console.log(num);      //try表示试一下有没有异常，而catch表示抓住异常
			}catch (abc){  //exception
				//console.log("num没有定义");
				console.log(abc);
			}
			console.log(123);
		}

		fn();
		fn();


		//自己抛出异常  throw
		//语法：throw 对象
		//一般对象是 new Error("错误消息");

		function fnError() {
			throw new Error("我是一个自定义错误");
		}
		function func() {
			fnError();
		}
		func();

	</script>
</head>
<body>
	
</body>
</html>